version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: nscs
      MYSQL_USER: vroomster
      MYSQL_PASSWORD: Vroomster123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
