import { GeneratorOptions } from '@prisma/generator-helper';
import {insertData} from "../../src/scripts/dataInserter";

const header = `// This file was generated by a custom prisma generator, do not edit manually.\n`;

export default async function onGenerate(options: GeneratorOptions) {
    const start = Date.now();

    const models = options.dmmf.datamodel.models;
    await insertData(models);
    const end = Date.now();
    console.log(`[custom-enum-generator] - Generated enums in ${end - start}ms`);
}
