import {
  // Crud Resolvers
  UserCrudResolver,
  AuthApplicationCrudResolver,
  AuthServiceCrudResolver,
  ApplicationServiceLinkCrudResolver,
  UserApplicationLinkCrudResolver,
  RoleCrudResolver,
  CRMObjectCrudResolver,
  CRMFieldCrudResolver,
  CRMObjectGroupCrudResolver,
  CRMObjectRelationsCrudResolver,
  CRMObjectPermissionCrudResolver,
  CRMFieldPermissionCrudResolver,
  BranchCrudResolver,
  ConsignorCrudResolver,
  ConsigneeCrudResolver,
  AirWayBillCrudResolver,
  AwbLineItemCrudResolver,
  AwbArticleCrudResolver,
  ConsignorRateTableCrudResolver,
  TripDetailsCrudResolver,
  TripCheckInCrudResolver,
  TripLineItemCrudResolver,
  ODACrudResolver,
  HLFLineItemCrudResolver,
  DEPSCrudResolver,
  DEPSImagesCrudResolver,
  FileUploadCrudResolver,
  ContractCrudResolver,
  AwbArticleTripLogsCrudResolver,
  SKUCrudResolver,
  InternalInvoiceCrudResolver,
  InternalInvoiceLineItemsCrudResolver,
  IndustryTypeMasterCrudResolver,
  PODCrudResolver,
  CommodityMasterCrudResolver,
  PincodesMasterCrudResolver,
  CityMasterCrudResolver,
  DistrictMasterCrudResolver,
  StateMasterCrudResolver,
  GstMasterCrudResolver,
  VendorMasterCrudResolver,
  VehicleMasterCrudResolver,
  DriverMasterCrudResolver,
  ViewHubLoadFactorCrudResolver,
  // Relation resolvers
  UserRelationsResolver,
  AuthApplicationRelationsResolver,
  AuthServiceRelationsResolver,
  ApplicationServiceLinkRelationsResolver,
  UserApplicationLinkRelationsResolver,
  RoleRelationsResolver,
  CRMObjectRelationsResolver,
  CRMFieldRelationsResolver,
  CRMObjectGroupRelationsResolver,
  CRMObjectRelationsRelationsResolver,
  CRMObjectPermissionRelationsResolver,
  CRMFieldPermissionRelationsResolver,
  BranchRelationsResolver,
  ConsignorRelationsResolver,
  ConsigneeRelationsResolver,
  AirWayBillRelationsResolver,
  AwbLineItemRelationsResolver,
  AwbArticleRelationsResolver,
  ConsignorRateTableRelationsResolver,
  TripDetailsRelationsResolver,
  TripCheckInRelationsResolver,
  TripLineItemRelationsResolver,
  ODARelationsResolver,
  HLFLineItemRelationsResolver,
  DEPSRelationsResolver,
  DEPSImagesRelationsResolver,
  FileUploadRelationsResolver,
  ContractRelationsResolver,
  AwbArticleTripLogsRelationsResolver,
  SKURelationsResolver,
  InternalInvoiceRelationsResolver,
  InternalInvoiceLineItemsRelationsResolver,
  IndustryTypeMasterRelationsResolver,
  PODRelationsResolver,
  CommodityMasterRelationsResolver,
  CityMasterRelationsResolver,
  DistrictMasterRelationsResolver,
  StateMasterRelationsResolver,
  GstMasterRelationsResolver,
  VendorMasterRelationsResolver,
  VehicleMasterRelationsResolver,
  DriverMasterRelationsResolver,
} from "@generated/type-graphql";
import { Authorized, NonEmptyArray, UseMiddleware } from "type-graphql";
import {
  ResolversEnhanceMap,
  ModelsEnhanceMap,
  applyResolversEnhanceMap,
  applyModelsEnhanceMap,
} from "@generated/type-graphql";
import { CreateManyGeneral } from "./components/customResolvers/CreateManyGeneral";
import { TripDetailsInterceptor } from "./components/middlewares/tripDetailsInterceptor";
import { ENUMS } from "./components/customResolvers/ENUMS";
import { ImportAwbLineItem } from "./components/customResolvers/ImportAwbLineItem";
import { RoleWizard } from "./components/customResolvers/RoleWizard";

const resolversEnhanceMap: ResolversEnhanceMap = {
  User: { _all: [Authorized()] },
  AuthApplication: { _all: [Authorized()] },
  AuthService: { _all: [Authorized()] },
  ApplicationServiceLink: { _all: [Authorized()] },
  UserApplicationLink: { _all: [Authorized()] },
  Role: { _all: [Authorized()] },
  Branch: { _all: [Authorized()] },
  CRMObject: { _all: [Authorized()] },
  CRMObjectGroup: { _all: [Authorized()] },
  Contract: { _all: [Authorized()] },
  CRMField: { _all: [Authorized()] },
  Consignee: { _all: [Authorized()] },
  Consignor: { _all: [Authorized()] },
  GstMaster: { _all: [Authorized()] },
  AirWayBill: { _all: [Authorized()] },
  AwbArticle: { _all: [Authorized()] },
  CityMaster: { _all: [Authorized()] },
  DEPSImages: { _all: [Authorized()] },
  FileUpload: { _all: [Authorized()] },
  AwbLineItem: { _all: [Authorized()] },
  HLFLineItem: { _all: [Authorized()] },
  StateMaster: { _all: [Authorized()] },
  TripCheckIn: { _all: [Authorized()] },
  TripDetails: {
    _all: [Authorized()],
    createOneTripDetails: [UseMiddleware(TripDetailsInterceptor)],
  },
  DriverMaster: { _all: [Authorized()] },
  TripLineItem: { _all: [Authorized()] },
  VendorMaster: { _all: [Authorized()] },
  VehicleMaster: { _all: [Authorized()] },
  DistrictMaster: { _all: [Authorized()] },
  PincodesMaster: { _all: [Authorized()] },
  ViewHubLoadFactor: { _all: [Authorized()] },
  AwbArticleTripLogs: { _all: [Authorized()] },
  CommodityMaster: { _all: [Authorized()] },
  CRMObjectPermission: { _all: [Authorized()] },
  ConsignorRateTable: { _all: [Authorized()] },
  CRMFieldPermission: { _all: [Authorized()] },
  IndustryTypeMaster: { _all: [Authorized()] },
  POD: { _all: [Authorized()] },
  SKU: { _all: [Authorized()] },
  DEPS: { _all: [Authorized()] },
  InternalInvoice: { _all: [Authorized()] },
  ODA: { _all: [Authorized()] },
  CRMObjectRelations: { _all: [Authorized()] },
};
applyResolversEnhanceMap(resolversEnhanceMap);

const modelsEnhanceMap: ModelsEnhanceMap = {
  User: { fields: { _all: [Authorized()] } },
  AuthApplication: { fields: { _all: [Authorized()] } },
  AuthService: { fields: { _all: [Authorized()] } },
  ApplicationServiceLink: { fields: { _all: [Authorized()] } },
  UserApplicationLink: { fields: { _all: [Authorized()] } },
  Role: { fields: { _all: [Authorized()] } },
  Branch: { fields: { _all: [Authorized()] } },
  CRMObject: { fields: { _all: [Authorized()] } },
  CRMObjectGroup: { fields: { _all: [Authorized()] } },
  Contract: { fields: { _all: [Authorized()] } },
  CRMField: { fields: { _all: [Authorized()] } },
  Consignee: { fields: { _all: [Authorized()] } },
  Consignor: { fields: { _all: [Authorized()] } },
  GstMaster: { fields: { _all: [Authorized()] } },
  AirWayBill: { fields: { _all: [Authorized()] } },
  AwbArticle: { fields: { _all: [Authorized()] } },
  CityMaster: { fields: { _all: [Authorized()] } },
  DEPSImages: { fields: { _all: [Authorized()] } },
  FileUpload: { fields: { _all: [Authorized()] } },
  AwbLineItem: { fields: { _all: [Authorized()] } },
  HLFLineItem: { fields: { _all: [Authorized()] } },
  StateMaster: { fields: { _all: [Authorized()] } },
  TripCheckIn: { fields: { _all: [Authorized()] } },
  TripDetails: { fields: { _all: [Authorized()] } },
  DriverMaster: { fields: { _all: [Authorized()] } },
  TripLineItem: { fields: { _all: [Authorized()] } },
  VendorMaster: { fields: { _all: [Authorized()] } },
  VehicleMaster: { fields: { _all: [Authorized()] } },
  DistrictMaster: { fields: { _all: [Authorized()] } },
  PincodesMaster: { fields: { _all: [Authorized()] } },
  ViewHubLoadFactor: { fields: { _all: [Authorized()] } },
  AwbArticleTripLogs: { fields: { _all: [Authorized()] } },
  CommodityMaster: { fields: { _all: [Authorized()] } },
  CRMObjectPermission: { fields: { _all: [Authorized()] } },
  ConsignorRateTable: { fields: { _all: [Authorized()] } },
  CRMFieldPermission: { fields: { _all: [Authorized()] } },
  IndustryTypeMaster: { fields: { _all: [Authorized()] } },
  POD: { fields: { _all: [Authorized()] } },
  SKU: { fields: { _all: [Authorized()] } },
  DEPS: { fields: { _all: [Authorized()] } },
  InternalInvoice: { fields: { _all: [Authorized()] } },
  ODA: { fields: { _all: [Authorized()] } },
  CRMObjectRelations: { fields: { _all: [Authorized()] } },
};
applyModelsEnhanceMap(modelsEnhanceMap);

export const generatedCrudResolvers: NonEmptyArray<Function> = [
  UserCrudResolver,
  AuthApplicationCrudResolver,
  AuthServiceCrudResolver,
  ApplicationServiceLinkCrudResolver,
  UserApplicationLinkCrudResolver,
  RoleCrudResolver,
  BranchCrudResolver,
  CRMObjectCrudResolver,
  CRMObjectGroupCrudResolver,
  CRMObjectRelationsCrudResolver,
  ContractCrudResolver,
  CRMFieldCrudResolver,
  ConsigneeCrudResolver,
  ConsignorCrudResolver,
  GstMasterCrudResolver,
  AirWayBillCrudResolver,
  AwbArticleCrudResolver,
  CityMasterCrudResolver,
  DEPSImagesCrudResolver,
  FileUploadCrudResolver,
  AwbLineItemCrudResolver,
  HLFLineItemCrudResolver,
  StateMasterCrudResolver,
  TripCheckInCrudResolver,
  TripDetailsCrudResolver,
  DriverMasterCrudResolver,
  TripLineItemCrudResolver,
  VendorMasterCrudResolver,
  VehicleMasterCrudResolver,
  DistrictMasterCrudResolver,
  PincodesMasterCrudResolver,
  ViewHubLoadFactorCrudResolver,
  AwbArticleTripLogsCrudResolver,
  CommodityMasterCrudResolver,
  CRMObjectPermissionCrudResolver,
  ConsignorRateTableCrudResolver,
  CRMFieldPermissionCrudResolver,
  IndustryTypeMasterCrudResolver,
  PODCrudResolver,
  SKUCrudResolver,
  ODACrudResolver,
  DEPSCrudResolver,
  InternalInvoiceCrudResolver,
  InternalInvoiceLineItemsCrudResolver,
];

export const generatedRelationResolvers: NonEmptyArray<Function> = [
  UserRelationsResolver,
  AuthApplicationRelationsResolver,
  AuthServiceRelationsResolver,
  ApplicationServiceLinkRelationsResolver,
  UserApplicationLinkRelationsResolver,
  RoleRelationsResolver,
  BranchRelationsResolver,
  CRMObjectRelationsResolver,
  CRMObjectGroupRelationsResolver,
  ContractRelationsResolver,
  CRMFieldRelationsResolver,
  ConsigneeRelationsResolver,
  ConsignorRelationsResolver,
  GstMasterRelationsResolver,
  AirWayBillRelationsResolver,
  AwbArticleRelationsResolver,
  CityMasterRelationsResolver,
  DEPSImagesRelationsResolver,
  FileUploadRelationsResolver,
  AwbLineItemRelationsResolver,
  HLFLineItemRelationsResolver,
  StateMasterRelationsResolver,
  TripCheckInRelationsResolver,
  TripDetailsRelationsResolver,
  DriverMasterRelationsResolver,
  TripLineItemRelationsResolver,
  VendorMasterRelationsResolver,
  VehicleMasterRelationsResolver,
  DistrictMasterRelationsResolver,
  AwbArticleTripLogsRelationsResolver,
  CommodityMasterRelationsResolver,
  CRMObjectPermissionRelationsResolver,
  ConsignorRateTableRelationsResolver,
  CRMFieldPermissionRelationsResolver,
  IndustryTypeMasterRelationsResolver,
  PODRelationsResolver,
  SKURelationsResolver,
  ODARelationsResolver,
  DEPSRelationsResolver,
  InternalInvoiceRelationsResolver,
  InternalInvoiceLineItemsRelationsResolver,
  CRMObjectRelationsRelationsResolver,
];

export const customResolvers: NonEmptyArray<Function> = [
  CreateManyGeneral,
  ImportAwbLineItem,
  ENUMS,
  RoleWizard,
];
