import {
    // Crud Resolvers
    UserCrudResolver,
    RoleCrudResolver,
    BranchCrudResolver,
    CRMTableCrudResolver,
    ContractCrudResolver,
    CRMColumnCrudResolver,
    ConsigneeCrudResolver,
    ConsignorCrudResolver,
    GstMasterCrudResolver,
    AirWayBillCrudResolver,
    AwbArticleCrudResolver,
    CityMasterCrudResolver,
    DEPSImagesCrudResolver,
    FileUploadCrudResolver,
    AwbLineItemCrudResolver,
    HLFLineItemCrudResolver,
    StateMasterCrudResolver,
    TripCheckInCrudResolver,
    TripDetailsCrudResolver,
    DriverMasterCrudResolver,
    TripLineItemCrudResolver,
    VendorMasterCrudResolver,
    VehicleMasterCrudResolver,
    DistrictMasterCrudResolver,
    PincodesMasterCrudResolver,
    ViewHubLoadFactorCrudResolver,
    AwbArticleTripLogsCrudResolver,
    CommodityMasterCrudResolver,
    CRMTablePermissionCrudResolver,
    ConsignorRateTableCrudResolver,
    CRMColumnPermissionCrudResolver,
    IndustryTypeMasterCrudResolver,
    // Relation resolvers
    UserRelationsResolver,
    RoleRelationsResolver,
    BranchRelationsResolver,
    CRMTableRelationsResolver,
    ContractRelationsResolver,
    CRMColumnRelationsResolver,
    ConsigneeRelationsResolver,
    ConsignorRelationsResolver,
    GstMasterRelationsResolver,
    AirWayBillRelationsResolver,
    AwbArticleRelationsResolver,
    CityMasterRelationsResolver,
    DEPSImagesRelationsResolver,
    FileUploadRelationsResolver,
    AwbLineItemRelationsResolver,
    HLFLineItemRelationsResolver,
    StateMasterRelationsResolver,
    TripCheckInRelationsResolver,
    TripDetailsRelationsResolver,
    DriverMasterRelationsResolver,
    TripLineItemRelationsResolver,
    VendorMasterRelationsResolver,
    VehicleMasterRelationsResolver,
    DistrictMasterRelationsResolver,
    AwbArticleTripLogsRelationsResolver,
    CommodityMasterRelationsResolver,
    CRMTablePermissionRelationsResolver,
    ConsignorRateTableRelationsResolver,
    CRMColumnPermissionRelationsResolver,
    IndustryTypeMasterRelationsResolver,
} from "@generated/type-graphql";
import { Authorized, NonEmptyArray } from "type-graphql";
import { ResolversEnhanceMap, ModelsEnhanceMap, applyResolversEnhanceMap, applyModelsEnhanceMap } from "@generated/type-graphql";

const resolversEnhanceMap: ResolversEnhanceMap = {
    User: { _all: [Authorized()] },
    Role: { _all: [Authorized()] },
    Branch: { _all: [Authorized()] },
    CRMTable: { _all: [Authorized()] },
    Contract: { _all: [Authorized()] },
    CRMColumn: { _all: [Authorized()] },
    Consignee: { _all: [Authorized()] },
    Consignor: { _all: [Authorized()] },
    GstMaster: { _all: [Authorized()] },
    AirWayBill: { _all: [Authorized()] },
    AwbArticle: { _all: [Authorized()] },
    CityMaster: { _all: [Authorized()] },
    DEPSImages: { _all: [Authorized()] },
    FileUpload: { _all: [Authorized()] },
    AwbLineItem: { _all: [Authorized()] },
    HLFLineItem: { _all: [Authorized()] },
    StateMaster: { _all: [Authorized()] },
    TripCheckIn: { _all: [Authorized()] },
    TripDetails: { _all: [Authorized()] },
    DriverMaster: { _all: [Authorized()] },
    TripLineItem: { _all: [Authorized()] },
    VendorMaster: { _all: [Authorized()] },
    VehicleMaster: { _all: [Authorized()] },
    DistrictMaster: { _all: [Authorized()] },
    PincodesMaster: { _all: [Authorized()] },
    ViewHubLoadFactor: { _all: [Authorized()] },
    AwbArticleTripLogs: { _all: [Authorized()] },
    CommodityMaster: { _all: [Authorized()] },
    CRMTablePermission: { _all: [Authorized()] },
    ConsignorRateTable: { _all: [Authorized()] },
    CRMColumnPermission: { _all: [Authorized()] },
    IndustryTypeMaster: { _all: [Authorized()] },
};
applyResolversEnhanceMap(resolversEnhanceMap);

const modelsEnhanceMap: ModelsEnhanceMap = {
    User: { fields: { _all: [Authorized()] } },
    Role: { fields: { _all: [Authorized()] } },
    Branch: { fields: { _all: [Authorized()] } },
    CRMTable: { fields: { _all: [Authorized()] } },
    Contract: { fields: { _all: [Authorized()] } },
    CRMColumn: { fields: { _all: [Authorized()] } },
    Consignee: { fields: { _all: [Authorized()] } },
    Consignor: { fields: { _all: [Authorized()] } },
    GstMaster: { fields: { _all: [Authorized()] } },
    AirWayBill: { fields: { _all: [Authorized()] } },
    AwbArticle: { fields: { _all: [Authorized()] } },
    CityMaster: { fields: { _all: [Authorized()] } },
    DEPSImages: { fields: { _all: [Authorized()] } },
    FileUpload: { fields: { _all: [Authorized()] } },
    AwbLineItem: { fields: { _all: [Authorized()] } },
    HLFLineItem: { fields: { _all: [Authorized()] } },
    StateMaster: { fields: { _all: [Authorized()] } },
    TripCheckIn: { fields: { _all: [Authorized()] } },
    TripDetails: { fields: { _all: [Authorized()] } },
    DriverMaster: { fields: { _all: [Authorized()] } },
    TripLineItem: { fields: { _all: [Authorized()] } },
    VendorMaster: { fields: { _all: [Authorized()] } },
    VehicleMaster: { fields: { _all: [Authorized()] } },
    DistrictMaster: { fields: { _all: [Authorized()] } },
    PincodesMaster: { fields: { _all: [Authorized()] } },
    ViewHubLoadFactor: { fields: { _all: [Authorized()] } },
    AwbArticleTripLogs: { fields: { _all: [Authorized()] } },
    CommodityMaster: { fields: { _all: [Authorized()] } },
    CRMTablePermission: { fields: { _all: [Authorized()] } },
    ConsignorRateTable: { fields: { _all: [Authorized()] } },
    CRMColumnPermission: { fields: { _all: [Authorized()] } },
    IndustryTypeMaster: { fields: { _all: [Authorized()] } },
};
applyModelsEnhanceMap(modelsEnhanceMap);

export const generatedCrudResolvers: NonEmptyArray<Function> = [
    UserCrudResolver,
    RoleCrudResolver,
    BranchCrudResolver,
    CRMTableCrudResolver,
    ContractCrudResolver,
    CRMColumnCrudResolver,
    ConsigneeCrudResolver,
    ConsignorCrudResolver,
    GstMasterCrudResolver,
    AirWayBillCrudResolver,
    AwbArticleCrudResolver,
    CityMasterCrudResolver,
    DEPSImagesCrudResolver,
    FileUploadCrudResolver,
    AwbLineItemCrudResolver,
    HLFLineItemCrudResolver,
    StateMasterCrudResolver,
    TripCheckInCrudResolver,
    TripDetailsCrudResolver,
    DriverMasterCrudResolver,
    TripLineItemCrudResolver,
    VendorMasterCrudResolver,
    VehicleMasterCrudResolver,
    DistrictMasterCrudResolver,
    PincodesMasterCrudResolver,
    ViewHubLoadFactorCrudResolver,
    AwbArticleTripLogsCrudResolver,
    CommodityMasterCrudResolver,
    CRMTablePermissionCrudResolver,
    ConsignorRateTableCrudResolver,
    CRMColumnPermissionCrudResolver,
    IndustryTypeMasterCrudResolver,
];

export const generatedRelationResolvers: NonEmptyArray<Function> = [
    UserRelationsResolver,
    RoleRelationsResolver,
    BranchRelationsResolver,
    CRMTableRelationsResolver,
    ContractRelationsResolver,
    CRMColumnRelationsResolver,
    ConsigneeRelationsResolver,
    ConsignorRelationsResolver,
    GstMasterRelationsResolver,
    AirWayBillRelationsResolver,
    AwbArticleRelationsResolver,
    CityMasterRelationsResolver,
    DEPSImagesRelationsResolver,
    FileUploadRelationsResolver,
    AwbLineItemRelationsResolver,
    HLFLineItemRelationsResolver,
    StateMasterRelationsResolver,
    TripCheckInRelationsResolver,
    TripDetailsRelationsResolver,
    DriverMasterRelationsResolver,
    TripLineItemRelationsResolver,
    VendorMasterRelationsResolver,
    VehicleMasterRelationsResolver,
    DistrictMasterRelationsResolver,
    AwbArticleTripLogsRelationsResolver,
    CommodityMasterRelationsResolver,
    CRMTablePermissionRelationsResolver,
    ConsignorRateTableRelationsResolver,
    CRMColumnPermissionRelationsResolver,
    IndustryTypeMasterRelationsResolver,
];